### ISSUE TITLE
Session cleaner - Add the ability to clean the files which don't exist?

### ISSUE THREAD

**Issue by stephen147** [STealthy-and-haSTy/SublimeScraps#23]
Hi,

I was wondering if it was possible to add cleaning the missing files from the `...\Sublime Text\Data\Local\Session.sublime_session` file also if that's not too much trouble?

I posted on the [ST forum](https://forum.sublimetext.com/t/is-there-a-way-to-clean-the-non-existant-files-from-session-sublime-session/48926/3):

> In the ...\Sublime Text\Data\Local\Session.sublime_session file there lies a lot of info relating to the session and other previous sessions.
I was wondering if anyone knows if someone that has written a ps or batch file to parse that file above and clean the folders and files that no longer exist.
I could write something myself but there’s no point in reinventing the wheel if someone has already done it.
Sublime Text has to be closed in order for this to happen so another way could be a new feature that could be added perhaps.

**Comment by FichteFoll** [comment]
Source: https://github.com/FichteFoll/FileHistory/issues/52

**Comment by OdatNurd** [comment]
That seems like it should be doable. In particular I would imagine that this would remove any files from the `file_history` and folders from the `folder_history` if they don't exist any longer.

As noted by @FichteFoll in the linked post, I think that would be an extra argument (or two, one for each) that you'd have to provide to get it to happen. 

Possibly it might also reverse the sense of the existing `--dry-run` flag so that instead of being able to see what it would do before you do it, that would be the default unless you tell it to go ahead. That might just be a good idea in general, though backups are kept before the run in case things go pear shaped.

**Comment by stephen147** [comment]
Oh, that would be great and if I understand correctly that call can be called from lets say a batch file `.cmd` to clean that file after ST closes.

I can automate this using Task Scheduler in Windows so that would be amazing!!

**Comment by OdatNurd** [comment]
I've got an (as yet unpublished) set of changes that implements this. I need to clean up the code a little bit and do some testing across all of the OS's that Sublime supports (currently only tested on Linux), so this should hopefully be pushed up and merged in early next week.

**Comment by stephen147** [comment]
This is great. Thank you so much. My history been set to 50 files will be much cleaner from now on.

**Comment by OdatNurd** [comment]
PR #24 has been submitted for review/sanity checking, which enhances the script to allow for cleaning up recently accessed files and folders as well as the existing ability to clean up workspaces/git repos.

With this change it's now required to specify on the command line one or more of `--workspaces`, `--folders` and `--files` to indicate what you'd like cleaned up, so that everyone has full control of what they would like to have trimmed out of their session information.

**Comment by stephen147** [comment]
Thanks. Have you any idea when this will be pushed to automatic updates in ST?

**Comment by OdatNurd** [comment]
The change will be merged in after it's been reviewed, but Keith is currently fairly busy so it could be a few days. In the meantime if you like you can take the version out of the PR branch to try it yourself (I personally tested it, the review is more for code quality/clarity and non-obvious bug checking type things). It does store a backup of the session before it modifies it just in case.

Not sure what you mean about automatic updates, though.

**Comment by stephen147** [comment]
Oh, by automatic updates I thought this was one of those plugins that were updated through ST. 

I can wait. Thanks.

**Comment by OdatNurd** [comment]
This has now been merged into `master` in commit b88af2e0 so you should be good to go. 

When you run the script, you need to provide at least one of `--workspaces`, `--files` or `--folders` depending on what you want to clean; (you can use more than one).  The script creates backups, but for a first run you might want to try it with `--dry-run` to see what it would do, particularly if you use any sort of network file share that's not currently mounted.

The README has more details as well.

**Comment by stephen147** [comment]
Thanks very much for this. If I have any bother I'll get back to you.

**Comment by stephen147** [comment]
Hi, I have the following code below saved as a batch file.

I'm running Windows 10. I'm pointing to a portable pyton.exe that I've placed in the same folder and then the `SessionCleaner.py` to run the `.py` file along with the other arguments as shown.

Python version I've downloaded is 3.8.

**RunSessionCleaner.cmd**
```
@echo off
"W:\Apps (Portable)\Sublime Text\Data\Packages\User\SessionCleaner\python\python.exe" "W:\Apps (Portable)\Sublime Text\Data\Packages\User\SessionCleaner\SessionCleaner.py" --data-dir "W:\Apps (Portable)\Sublime Text\sublime_text.exe" --workspaces --files --folders
pause
```

It gives me the error in the command line.

```
INFO:root:Using Data Directory: W:\Apps (Portable)\Sublime Text\Data\Local\Session.sublime_session
ERROR:root:Unable to locate session file
Traceback (most recent call last):
  File "W:\Apps (Portable)\Sublime Text\Data\Packages\User\SessionCleaner\SessionCleaner.py", line 65, in load_session
    with open(file_name, encoding="utf-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'W:\\Apps (Portable)\\Sublime Text\\Data\\Local\\Session.sublime_session\\Local\\Session.sublime_session'
Press any key to continue . . .
```

**Comment by OdatNurd** [comment]
The `Data` directory is the place where Sublime is storing your user configuration items. In particular, if you're using a portable copy of Sublime it's literally a folder named `Data` that's inside of the installation folder of Sublime.

You can find it from Sublime by using `Preferences > Browse Packages` from the menu or command palette to open the `Packages` folder, and then go up one folder. Whatever folder you're in, that's your `Data` directory.

In your case, I think you just need to replace the `sublime_text.exe` part of your path with `Data`.

**Comment by stephen147** [comment]
Cheers very much :)

This is my working batch file.

```
@echo off & title %~nx0 & color 5F & chcp 65001 >NUL
:: Full path to data folder        W:\Apps (Portable)\Sublime Text\Data
:: Full path to python.exe         W:\Apps (Portable)\Sublime Text\Data\Packages\User\SessionCleaner\python\python.exe
:: Full path to SessionCleaner.py  W:\Apps (Portable)\Sublime Text\Data\Packages\User\SessionCleaner\SessionCleaner.py
".\python\python.exe" "SessionCleaner.py" --data-dir "..\..\..\..\Data" --workspaces --files --folders
```

**Comment by stephen147** [comment]
Sorry to bother you again but is it possible to specify other folders where I store my projects and not the active project for projects within the data root folder or is that outside the scope of this plugin?

As it currently stands it cleans the currently loaded project but not the others of the 5 projects in the folder below.

I have 5 projects in this folder:
`W:\Apps (Portable)\Sublime Text\Data\Packages\User\Projects`

Or should I just move them to the folder:
`W:\Apps (Portable)\Sublime Text\Data\`

Does the script recursively go through all levels of the data folder?

**Comment by OdatNurd** [comment]
This script only cleans the session file itself, not the `sublime-workspace` files that are associated with projects themselves. If I recall correctly, the session file and the workspace files have the same structure, so this could perhaps be used to clean up workspace files as well with a bit more work.

I'm not sure if that's entirely within the scope of what this is trying to do, though. I'll have to ponder if that's an easy thing to add here or if perhaps we want a second script for that.

**Comment by stephen147** [comment]
Oh, I see. When I checked initially I thought the session file had all that info contained there.

Adding this would really be extremely useful. If you have a donate link so I could contribute at least something towards your efforts.

**Comment by OdatNurd** [comment]
The session file is sort of a global version of a local workspace file; when you're using Projects they effectively maintain their own session, which is where information like the window layout, unsaved contents and such are stored for projects. 

If you renamed the `sublime-workspace` file that was associated with a project (they generally have the same name as the `sublime-project` file unless you manually changed it) while the project was closed and then re-opened the project, you'd get a completely new session.

That should clear all of the information about recent files and folders (so long as you run this script to clean the session file first) and give your workspace a clean slate, but it would also drop the information on the files you had open, the window layout, find history, etc. 

If you decide to try that, make sure that you save all of your files before you close the project because the content of unsaved files is persisted in the workspace file.

Are you using one of the 4xxx builds of Sublime (they're currently only available on the Discord server)? Those versions include some new API functions that I think could be used to create a plugin similar to this script that could clean the workspace from directly inside of Sublime. 

There's not really a good way to do that sort of thing in Sublime Text 3, though; at best such a plugin would require you to manually tell it what file to clean and rely on you to not have it open at the time.

**Comment by stephen147** [comment]
I'll take a look and see but I thought you had to pay for those insider builds. 

I can wait for this added functionality and I'm super happy to have this though. I can always clean switch to the project and close ST and reopen it. I've created an automatic task to run the cleaner when ST is open. So switching the project and closing is no big deal for now.

I will wait until 4.0 is out. Thanks very much.

**Comment by FichteFoll** [comment]
> Are you using one of the 4xxx builds of Sublime (they're currently only available on the Discord server)? Those versions include some new API functions that I think could be used to create a plugin similar to this script that could clean the workspace from directly inside of Sublime.

Are you thinking of the on_exit handler?

**Comment by OdatNurd** [comment]
In this case, no (although Keith and I were speculating on whether that might trigger after the session is written). I was thinking more of the new APIs/commands for being able to determine the current workspace in use in a window and open projects. 

The idea being that a plugin command could close the project in the window, clean the workspace, and then open it again.

**Comment by FichteFoll** [comment]
Ah, yes, that would be better solution without having to restart ST.
